//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyResponse()
        {
            this.ResponseAnswers = new HashSet<ResponseAnswer>();
        }
    
        public int SurveyResponseID { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public Nullable<int> VisitorID { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string FillFromSiteUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseAnswer> ResponseAnswers { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
