//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Surveys = new HashSet<Survey>();
        }
    
        public int UserID { get; set; }
        public string UserEmailID { get; set; }
        public string Password { get; set; }
        public Nullable<int> SurveyCreated { get; set; }
        public string Username { get; set; }
        public string Designation { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<bool> IsEmailVarify { get; set; }
        public string ResetPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey> Surveys { get; set; }
    }
}
